NUM_GATES = 11
BITS_PER_GATE = 4
BITS_PER_GENE = 1 + 2 * BITS_PER_GATE  # 1 bit for if the gene can be Baldwin Effect'd
BITS_PER_GENOME = BITS_PER_GENE * NUM_GATES + 4

BALDWIN_ITERS = 100

CROSSOVER_P = 0.5
MUTATION_P = 0.5 / BITS_PER_GENOME

POPULATION_SIZE = 5000
CHUNK_SIZE = 100
GRADUATION_SIZE = 1500  # number of organisms that move to the next generation

GENERATIONS = 100000
LOG_STEP = 10
GOAL_CHANGE_T = 20

EXP_FACTOR = 30

CHANGE_GOAL = True

USING_MODAL = True
